language: node_js
node_js:
  - "12.13"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./src/sfxWeb/node_modules
before_install:
  - npm install -g npm@latest
install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install fakeroot; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install rpm; fi
  - npm install -g gulp-cli
  - npm install @angular/cli -g
  - pushd ./src/SfxWeb; npm install
script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - pushd ./src/SfxWeb; ng build --prod